### ISSUE TITLE
hiredis-rb fails with hiredis master

### ISSUE THREAD

**Issue by thedrow** [redis/hiredis-rb#33]
https://travis-ci.org/redis/hiredis/jobs/43192929#L245 Only two failures.
Can you please fix them?

**Comment by badboy** [comment]
Rekicked tests. Looks like a temporary error, can't reproduce locally.

**Comment by badboy** [comment]
Hmpf, these tests are somehow broken. Need to look further into this.

**Comment by badboy** [comment]
I will probably remove these tests for now.
