### ISSUE TITLE
Hiredis and ruby 2.2

### ISSUE THREAD

**Issue by looseend** [redis/hiredis-rb#34]
I upgraded to ruby 2.2 and got this error:

```
dyld: lazy symbol binding failed: Symbol not found: _rb_thread_select
  Referenced from: /Users/jsinglet/.rvm/gems/ruby-2.2.0/extensions/x86_64-darwin-14/2.2.0/hiredis-0.4.5/hiredis/ext/hiredis_ext.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_thread_select
  Referenced from: /Users/jsinglet/.rvm/gems/ruby-2.2.0/extensions/x86_64-darwin-14/2.2.0/hiredis-0.4.5/hiredis/ext/hiredis_ext.bundle
  Expected in: flat namespace
```

Seems like the _rb_thread_select method has been renamed to rb_thread_fd_select in ruby 2.2

Downgrading to ruby 2.1.5 makes this issue go away

https://bugs.ruby-lang.org/issues/9502

**Comment by OrelSokolov** [comment]
:+1:

**Comment by badboy** [comment]
Did you recompile after updating?
If not, that's the issue. If you did, can you try with the `new-release` branch? https://github.com/redis/hiredis-rb/tree/new-release

**Comment by looseend** [comment]
I've updated and it's working fine now thanks.

**Comment by badboy** [comment]
Thanks, I'll get the release done this week.
