### ISSUE TITLE
RuntimeError sucks

### ISSUE THREAD

**Issue by fw42** [redis/hiredis-rb#40]
Hey,

I noticed a small annoyance and inconsistency:

```
irb(main):004:0> Redis.new(host: "foobar").get('bar')
SocketError: getaddrinfo: Name or service not known
```

vs.

```
irb(main):006:0> Redis.new(host: "foobar", driver: 'hiredis').get('bar')
RuntimeError: Name or service not known
```

The Ruby driver raises SocketError while the hiredis driver raises RuntimeError. I would argue that SocketError is better because RuntimeError is very vague and harder to rescue in a meaningful way. Whatever your opinion on this is, I think both drivers should ideally raise the same error.

Thoughts?

@badboy

**Comment by badboy** [comment]
I can see the problem, for some reason it always been this way, so whatever we do will be a breaking change, so I'm kinda restrained doing that change.
I will get in contatc with @djanowski

**Comment by fw42** [comment]
Any chance to get this fixed? I can make a PR if there's any interest.

**Comment by badboy** [comment]
Yes, please. Let's fix that now

**Comment by erated** [comment]
Any updates on this? Runtime error sucks and prevents from creating real error handling.
"RuntimeError: Name or service not known". These are cluttering our logs and making me think that we should potentially switch back to the default redis client as we cant handle these gracefully.
