### ISSUE TITLE
New maintainer needed

### ISSUE THREAD

**Issue by badboy** [redis/hiredis-rb#49]
I have neither the time nor the energy to fulfil the maintainer role here.
I failed to spend enough time in the past and haven't pushed out a release in nearly 3 years.

If anyone is actively using this project and wants to take over, please reach me over email.

**Comment by rafaelfranca** [comment]
@badboy it looks like we can release the gem but we can't write to the repository. Can you give the redis-rb team write access to this repository?

**Comment by badboy** [comment]
Woops, checking.

**Comment by badboy** [comment]
Sorry about that hiccup. Admin/write enabled for the redis-rb team. Closing here.
