### ISSUE TITLE
No releases on rubygems?

### ISSUE THREAD

**Issue by ixti** [redis/hiredis-rb#60]
The latest release version on rubygems is 0.6.3 which is far behind the changelog. When will new releases be pushed to rubygems?

**Comment by byroot** [comment]
The only unpublished change is a simple typo. 

Are you sure you aren't confusing the gem version with a c library version? `hiredis-rb` `0.6.3` uses the `0.14` c library.

**Comment by ixti** [comment]
Oops. Sorry, indeed.
