### ISSUE TITLE
AppVeyor tests fail due to Bundler version mismatch

### ISSUE THREAD

**Issue by olleolleolle** [redis/hiredis-rb#65]
The AppVeyor tests run on 2.1 and 2.2, it seems, and they both fail.

"Too new Bundler" for those.

> gem install bundler --no-document
> ERROR:  Error installing bundler:
> 	The last version of bundler (>= 0) to support your Ruby & RubyGems was 1.17.3. Try installing it with `gem install bundler -v 1.17.3`
> 	bundler requires Ruby version >= 2.3.0. The current ruby version is 2.1.0.
>

**Comment by michael-grunder** [comment]
Closing as this is fixed.
