### ISSUE TITLE
SSL not supported by hiredis driver message

### ISSUE THREAD

**Issue by razasayed** [redis/hiredis-rb#79]
Im using the latest version of redis-rb which is version 4.6.0 and also of hiredis gem, version 0.6.3. Im trying to connect to a Redis cluster in AWS which has in transit encryption enabled as follows:

client = Redis.new(url: 'the url here', ssl: true)

I get the following response:

NotImplementedError (SSL not supported by hiredis driver)

Also, tying to do client = Redis.new(url: 'the url here', ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }) leads to a Connection Timeout.

I saw that hiredis C library has enabled SSL support (https://github.com/redis/hiredis/pull/645 ). However, is SSL support still not available in the ruby version ?. Is there any other way to get SSL working with redis in ruby ?

**Comment by swrobel** [comment]
Did you figure out a resolution for this? If so, can you share it here?
